spring:
  datasource:
    url: jdbc:h2:mem:bmms
    #jdbc:h2:file:/data/bmms
    username: spring
    password: spring
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create

  h2:
    console:
      enabled: true