spring:
  datasource:
    url: jdbc:h2:mem:mydb #jdbc:h2:file:/data/bmms
    username: spring
    password: spring
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true